version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    expose:
      - ${DATABASE_PORT} 
    networks:
      - mynet


  django:
    build:
      dockerfile: DockerFile
      args:
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USER=${DATABASE_USER}
        - DATABASE_PASS=${DATABASE_PASS}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_PORT=${DATABASE_PORT}
        - SECRET_KEY=${SECRET_KEY}
        - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    ports:
      - "8080:8080"
    expose:
      - '8080'
    networks:
      - mynet



networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
