version: '3.3'
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
    networks:
      - mynet
  django:
    build:
      args:
        - BRANCH=${BRANCH}
      dockerfile: DockerFile
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    command: "poetry run python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database
    ports:
      - "8000:8000"
    expose:
      - '8000'
    networks:
      - mynet

networks:
  mynet: 
    driver: bridge
    ipam:
      driver: default
