name: "Install dependencies"
description : "installs poetry" 

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
      shell: bash
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - run: poetry install   
      shell: bash
