name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: UnsafePassword098
          MYSQL_DATABASE: mysql
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry update
        
    - name: Run Migrations
      run: poetry run python manage.py migrate
      env:
        DBENGINE: django.db.backends.mysql
        DBNAME: answerking_app
        DBUSER: root
        DBPASSWORD: UnsafePassword098
        DBHOST: 127.0.0.1
        DBPORT: 3306
        
    - name: Run Tests     
      run: |
        poetry run python manage.py test
      env:
        DBENGINE: django.db.backends.mysql
        DBNAME: answerking_app
        DBUSER: root
        DBPASSWORD: UnsafePassword098
        DBHOST: 127.0.0.1
        DBPORT: 3306
