name: Integration Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASS }}
          MYSQL_DATABASE: answerking_app
        ports: [ '3306:3306' ]
    env:
      DATABASE_NAME: answerking_app
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 3306
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DJANGO_SETTINGS_MODULE: answerking.settings.development
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dependencies
      - name: Run Integration Tests
        run: poetry run python manage.py test answerking_app.tests.test_integration
