name: Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results


jobs:
  test_and_sonar_cloud_report:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASS }}
          MYSQL_DATABASE: answerking_app
        ports: ['3306:3306']
    env:
        DATABASE_NAME: answerking_app
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 3306
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_SETTINGS_MODULE: answerking.settings.development
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
    steps:
      - uses : actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/dependencies
      - uses: SonarSource/sonarcloud-github-action@master
      - name: Run Migrations
        run: |
          poetry run python manage.py migrate
      - name: Run Unit Tests
        run: poetry run python manage.py test
      - name: generate coverage tests
        run: poetry run coverage run --omit=*/migrations/*,*/answerking/* manage.py test --noinput
      - name: generate report
        run: poetry run coverage xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
